routes/admin.php
<?php


use Illuminate\Support\Facades\Route;

Route::get('/', 'LoginController@index')->name('login');
Route::get('login', 'LoginController@index')->name('login');
Route::post('login', 'LoginController@loginCheck')->name('loginCheck');
Route::group(['middleware' => ['auth:admin', 'adminLanguage']], function () {

    Route::get('dashboard', 'HomeController@index')->name('dashboard');
    Route::resource('category', 'CategoryController');
    Route::resource('user', 'UserController');
    Route::get('userDetails/{id}', 'UserController@userDetails')->name('userDetails');
    Route::get('user/status/{id}/{status}', 'UserController@changeStatus')->name('user.status.change');
    Route::get('user/approve/{id}/{status}', 'UserController@changeApproveStatus')->name('user.approve.change');

    Route::get('profile', 'AdminController@profile')->name('profile');
    Route::post('updateProfile', 'AdminController@updateProfile')->name('updateProfile');
    Route::get('changePassword', 'AdminController@changePassword')->name('changePassword');
    Route::post('updatePassword', 'AdminController@updatePassword')->name('updatePassword');

    Route::post('editProfile', 'HomeController@editProfile')->name('editProfile');
    Route::post('logout', 'LoginController@logout')->name('logout');
    Route::get('/', 'LoginController@index');
    Route::get('dashboard', 'HomeController@index')->name('dashboard');
    Route::get('/logout', 'LoginController@logout')->name('logout');

    Route::post('getState', 'HomeController@getState')->name('getState');
    Route::post('getCity', 'HomeController@getCity')->name('getCity');


    Route::resource('role', 'RoleController');
    Route::resource('permission', 'PermissionController');


    Route::resource('users', 'UserController');
    Route::resource('country', 'CountryController');
    Route::resource('state', 'StateController');
    Route::resource('city', 'CityController');
    Route::get('/pendingUser', 'UserController@pending')->name('pendingUser');
    Route::get('/incompleteUser', 'UserController@incomplete')->name('incompleteUser');
    Route::get('/approvedUser', 'UserController@approved')->name('approvedUser');

    Route::post('getState', 'StateController@getState')->name('getState');
    Route::get('country/status/{id}/{status}', 'CountryController@changeStatus')->name('country.status.change');
    Route::get('state/status/{id}/{status}', 'StateController@changeStatus')->name('state.status.change');
    Route::post('getCity', 'CityController@getCity')->name('getCity');
    Route::get('city/status/{id}/{status}', 'CityController@changeStatus')->name('city.status.change');
    Route::get('role/status/{id}/{status}', 'RoleController@changeStatus')->name('role.status.change');


    Route::resource('page', 'PageController');
    Route::resource('notification', 'NotificationController');

    Route::get('setting', 'SettingController@index')->name('setting');
    Route::get('sendNotification', 'SendController@sendNotification')->name('sendNotification');
    Route::post('sendNotification', 'SendController@sendNotificationProcess')->name('sendNotification');


    Route::post('updateSetting', 'SettingController@updateSetting');

    Route::get('test', 'HomeController@test')->name('test');

    Route::get('export/{id}', 'DirectSellerController@export')->name('export');
    Route::post('customerSearch', 'PurchaseOrderController@customerSearch')->name('customerSearch');

    Route::resource('slider', 'SliderController');
    Route::resource('template', 'TemplateController');
    Route::resource('gotra', 'GotraController');
    Route::resource('workProfile', 'WorkProfileController');
    Route::resource('subAdmin', 'SubAdminController');
    Route::resource('mangalik', 'MangalikController');
    Route::resource('highestEducation', 'HighestEducationController');
    Route::resource('adminLog', 'AdminLogController');
    Route::get('pending-subAdmin', 'SubAdminController@pending')->name('subAdmin.pending');
    Route::get('approved-subAdmin', 'SubAdminController@approved')->name('subAdmin.approved');
    Route::get('rejected-subAdmin', 'SubAdminController@rejected')->name('subAdmin.rejected');
    Route::get('subAdmin/registerStatus/{id}/{status}', 'SubAdminController@changeRegisterStatus')->name('subAdmin.register-status.change');
    Route::get('subAdmin/status/{id}/{status}', 'SubAdminController@changeStatus')->name('subAdmin.status.change');
    Route::post('assignRole', 'SubAdminController@assignRole')->name('assignRole');
    Route::post('rejectSubAdmin', 'SubAdminController@rejectSubAdmin')->name('rejectSubAdmin');
    Route::post('banUser', 'UserController@banUser')->name('banUser');
    Route::get('fileImportExport', 'UserController@fileImportExport')->name('fileImportExport');
    Route::post('fileImport', 'UserController@fileImport')->name('fileImport');
    Route::get('report', 'ReportController@index')->name('report');
    Route::resource('homeBanner', 'HomeBannerController');
    Route::get('analytics', 'HomeController@analytics')->name('analytics');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', 'HomeController@index')->name('home');
Route::get('/verify-email', 'AuthController@verifyEmail')->name('verify-email');
Route::get('/register', 'AuthController@register')->name('register');
Route::get('/contact-us', 'HomeController@contactUs')->name('contact-us');
Route::post('/register', 'AuthController@registerSubmit')->name('register');
Route::get('/login', 'AuthController@login')->name('login');
Route::get('/page/{slug}', 'PageController@index')->name('page');
Route::get('/forgot-password', 'AuthController@forgotPasswordForm')->name('forgot-password');
Route::get('/reset-password/{id}', 'ResetPasswordController@resetPasswordForm')->name('reset-password');
Route::post('/resetPassword', 'ResetPasswordController@resetPassword')->name('resetPassword');
Route::post('/forgotPassword', 'AuthController@forgotPassword')->name('forgotPassword');
Route::post('/login', 'AuthController@loginSubmit')->name('login');
Route::get('/passwordReset', 'AuthController@passwordReset')->name('password.request');
Route::get('/logout', 'AuthController@logout')->name('logout');
Route::get('/happy_stories', 'HomeController@happy_stories')->name('happy_stories');
Route::get('/getState/{id}', 'HomeController@getState')->name('getState');
Route::get('/getCity/{id}', 'HomeController@getCity')->name('getCity');
Route::get('/verify-otp', 'AuthController@verifyOtpForm')->name('verify-otp');
Route::post('/verifyOtp', 'AuthController@verifyOtp')->name('verifyOtp');
Route::get('/admin-form', 'AuthController@adminForm')->name('admin-form');
Route::get('/blocked', 'HomeController@user_account_blocked')->name('user.blocked');
Route::get('resend-otp', 'AuthController@resend_otp')->name('resend-otp');
Route::post('/adminForm', 'AuthController@adminFormSubmit')->name('adminForm');

Route::group(['middleware' => ['auth:web']], function () {
    Route::post('/introduction-update', 'ProfileController@introductionUpdate')->name('introduction-update');
    Route::post('/basic_info_update', 'ProfileController@basic_info_update')->name('basic_info_update');
    Route::post('/update_education_present_status', 'ProfileController@update_education_present_status')->name('update_education_present_status');
    Route::post('/address-update', 'ProfileController@addressUpdate')->name('address-update');
    Route::post('/hobbies-update', 'ProfileController@hobbiesUpdate')->name('hobbies-update');
    Route::post('/recidencies-update', 'ProfileController@recidenciesUpdate')->name('recidencies-update');
    Route::post('/photos-update', 'ProfileController@photosUpdate')->name('photos-update');
    Route::post('/native-address-update', 'ProfileController@nativeAddressUpdate')->name('native-address-update');
    Route::post('/families-update', 'ProfileController@familiesUpdate')->name('families-update');
    Route::post('/education-update', 'ProfileController@educationUpdate')->name('education-update');
    Route::post('/change-email', 'ProfileController@changeEmail')->name('change-email');
    Route::post('/add_to_ignore_list', 'ProfileController@add_to_ignore_list')->name('add_to_ignore_list');
    Route::post('/reportUsers', 'ProfileController@reportUsers')->name('reportUsers');
    Route::post('approve-status-update', 'ProfileController@submitForApproval')->name('approve-status-update');
    Route::post('socialMediaUpdate', 'ProfileController@socialMediaUpdate')->name('socialMediaUpdate');
    Route::get('checkProfile', 'ProfileController@checkProfile')->name('checkProfile');
    Route::get('update_account_deactivation_status', 'ProfileController@update_account_deactivation_status')->name('update_account_deactivation_status');
    Route::group(['middleware' => ['member']], function () {
        Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');
        Route::get('/memberListing', 'MemberListingController@index')->name('memberListing');
        Route::get('/change_password', 'ProfileController@change_password')->name('change_password');
        Route::get('/profile_settings', 'ProfileController@profile_settings')->name('profile_settings');
        Route::get('/my_interests', 'ProfileController@my_interests')->name('my_interests');

        Route::get('/member_profile/{id}', 'ProfileController@member_profile')->name('member_profile');

        Route::get('/view_contacts', 'ProfileController@view_contacts')->name('view_contacts');
        Route::get('/remove_video', 'ProfileController@remove_video')->name('remove_video');
        Route::get('/add_to_ignore_list', 'ProfileController@add_to_ignore_list')->name('add_to_ignore_list');
        Route::resource('happy-story', 'HappyStoryController');

        Route::get('/ignored-list', 'IgnoredUserController@index')->name('my_ignored_list');
        Route::post('/remove_from_ignored_list-list', 'IgnoredUserController@remove_from_ignored_list')->name('remove_from_ignored_list');

        Route::get('/my-interests', 'ExpressInterestController@index')->name('my_interests.index');
        Route::get('/interest/requests', 'ExpressInterestController@interest_requests')->name('interest_requests');
        Route::post('/interest/accept', 'ExpressInterestController@accept_interest')->name('accept_interest');
        Route::post('/interest/reject', 'ExpressInterestController@reject_interest')->name('reject_interest');
        Route::resource('/express-interest', 'ExpressInterestController');
        Route::get('change-password', 'ProfileController@change_password')->name('change_password');
        Route::post('password_update', 'ProfileController@password_update')->name('password_update');


    });
});

resources/views/web/member/dashboard.blade.php
@extends('web.layouts.member_panel')
@section('panel_content')
    @php $user = Auth::user(); @endphp
    <div class="row gutters-5">
        <div class="col-md-4 mx-auto mb-3">
            <a href="{{route('interest_requests')}}">
                <div class="bg-light rounded overflow-hidden text-center p-3">
                    <i class="la la-heart-o la-3x mb-3 text-primary-grad"></i>
                    <div class="h4 fw-700 text-primary-grad">{{ $interest_requests }}</div>
                    <div class="" style="color:black">Interest Requests</div>
                </div>
            </a>

        </div>
        <div class="col-md-4 mx-auto mb-3">
            <a href="{{route('my_interests.index')}}">
            <div class="bg-light rounded overflow-hidden text-center p-3">
                <i class="la la-heart-o la-3x mb-3 text-primary-grad"></i>
                <div class="h4 fw-700 text-primary-grad">{{$my_interests}}</div>
                <div class="" style="color:black">My Interests</div>
            </div>
            </a>
        </div>
        <div class="col-md-4 mx-auto mb-3">
            <a href="{{route('my_ignored_list')}}">
            <div class="bg-light rounded overflow-hidden text-center p-3">
                <i class="las la-image la-3x mb-3 text-primary-grad"></i>
                <div class="h4 fw-700 text-center text-primary-grad">{{$ingored_members}}</div>
                <div class="text-center" style="color:black">Ignored Members</div>
            </div>
            </a>
        </div>
    </div>
{{--    <div class="row gutters-5">--}}
{{--        <div class="col-md-12">--}}
{{--            <div class="card">--}}
{{--                <div class="card-header">--}}
{{--                    <h2 class="fs-16 mb-0">Matched profile</h2>--}}
{{--                </div>--}}
{{--                <div class="card-body">--}}
{{--                    <div>--}}
{{--                        @forelse ($similar_profiles->shuffle()->take(5) as $similar_profile)--}}
{{--                            @if($similar_profile->matched_profile != null)--}}
{{--                                <a href="{{ route('member_profile', $similar_profile->match_id) }}"--}}
{{--                                   class="text-reset border rounded row no-gutters align-items-center mb-3">--}}
{{--                                    <div class="col-auto w-100px">--}}
{{--                                        <img--}}
{{--                                                src="{{ asset($similar_profile->matched_profile->image) }}"--}}
{{--                                                onerror="this.onerror=null;this.src='{{ asset('assets/img/avatar-place.png') }}';"--}}
{{--                                                class="img-fit w-100 size-100px"--}}
{{--                                        >--}}
{{--                                    </div>--}}
{{--                                    <div class="col">--}}
{{--                                        <div class="p-3">--}}
{{--                                            <h5 class="fs-16 text-body text-truncate">{{ $similar_profile->matched_profile->first_name.' '.$similar_profile->matched_profile->last_name }}</h5>--}}
{{--                                            <div class="fs-12 text-truncate-3">--}}
{{--                                          <span class="mr-1 d-inline-block">--}}
{{--                                            @if(!empty($similar_profile->matched_profile->date_of_birth))--}}
{{--                                                  {{ \Carbon\Carbon::parse($similar_profile->matched_profile->date_of_birth)->age }}--}}
{{--                                                  Years.--}}
{{--                                                  ,--}}
{{--                                              @endif--}}
{{--                                          </span>--}}
{{--                                                <span class="mr-1 d-inline-block">--}}
{{--                                            @if(!empty($similar_profile->matched_profile->profile->height))--}}
{{--                                                        {{ $similar_profile->matched_profile->profile->height }} Feet--}}
{{--                                                        ,--}}
{{--                                                    @endif--}}
{{--                                          </span>--}}
{{--                                                <span class="mr-1 d-inline-block">--}}
{{--                                            @if(!empty($similar_profile->matched_profile->profile->marital_status))--}}
{{--                                                        {{ $similar_profile->matched_profile->member->marital_status }}--}}
{{--                                                        ,--}}
{{--                                                    @endif--}}
{{--                                          </span>--}}
{{--                                                <span class="mr-1 d-inline-block">--}}
{{--                                            {{ !empty($similar_profile->matched_profile->profile->self_intro_text) ? $similar_profile->matched_profile->profile->self_intro_text.', ' : "" }}--}}
{{--                                          </span>--}}
{{--                                            </div>--}}
{{--                                        </div>--}}
{{--                                    </div>--}}
{{--                                </a>--}}
{{--                            @endif--}}
{{--                        @empty--}}
{{--                            <div--}}
{{--                                    class="alert alert-info">No data found--}}
{{--                            </div>--}}
{{--                        @endforelse--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}


@endsection

resources/views/web/member/my_shortlists.blade.php
@extends('web.layouts.member_panel')
@section('panel_content')
    <div class="card">
        <div class="card-header">
            <h5 class="mb-0 h6">{{ trans('messages.My Shortlists') }}</h5>
        </div>
        <div class="card-body">
            <table class="table aiz-table mb-0">
              <thead>
                  <tr>
                      <th>#</th>
                      <th>{{trans('messages.Image')}}</th>
                      <th>{{trans('messages.Name')}}</th>
                      <th>{{trans('messages.Age')}}</th>
                      @if(get_setting('member_spiritual_and_social_background_section') == 'on')
                      <th>{{trans('messages.Religion')}}</th>
                      @endif
                      @if(get_setting('member_present_address_section') == 'on')
                      <th>{{trans('messages.Location')}}</th>
                      @endif
                      @if(get_setting('member_language_section') == 'on')
                      <th>{{trans('messages.Mother Tongue')}}</th>
                      @endif
                      <th class="text-right">{{trans('messages.Options')}}</th>
                  </tr>
              </thead>
              <tbody>
                  @foreach ($shortlists as $key => $shortlist)
                      @if($shortlist->user != null)
                      <tr id="shortlisted_member_{{ $shortlist->user_id }}">
                          <td>{{ ($key+1) + ($shortlists->currentPage() - 1)*$shortlists->perPage() }}</td>
                          <td>
                            <a
                              @if(get_setting('full_profile_show_according_to_membership') == 1 && Auth::user()->membership == 1)
                                  href="javascript:void(0);" onclick="package_update_alert()"
                              @else
                                  href="{{ route('member_profile', $shortlist->user_id) }}"
                              @endif
                              class="text-reset c-pointer"
                            >
                                @if(uploaded_asset($shortlist->user->photo) != null)
                                    <img class="img-md" src="{{ uploaded_asset($shortlist->user->photo) }}" height="45px"  alt="{{trans('messages.photo')}}">
                                @else
                                    <img class="img-md" src="{{ asset('assets/img/avatar-place.png') }}" height="45px"  alt="{{trans('messages.photo')}}">
                                @endif
                            </a>
                          </td>
                          <td>
                              <a
                                @if(get_setting('full_profile_show_according_to_membership') == 1 && Auth::user()->membership == 1)
                                    href="javascript:void(0);" onclick="package_update_alert()"
                                @else
                                    href="{{ route('member_profile', $shortlist->user_id) }}"
                                @endif
                                class="text-reset c-pointer"
                              >
                                {{ $shortlist->user->first_name.' '.$shortlist->user->last_name }}
                            </a>
                          </td>
                          <td>{{ \Carbon\Carbon::parse($shortlist->user->member->birthday)->age }}</td>
                          @if(get_setting('member_spiritual_and_social_background_section') == 'on')
                          <td>
                            @if(!empty($shortlist->user->spiritual_backgrounds->religion_id))
                                {{ $shortlist->user->spiritual_backgrounds->religion->name }}
                            @endif
                          </td>
                          @endif
                          @if(get_setting('member_present_address_section') == 'on')
                          <td>
                            @php
                                $present_address = \App\Models\Address::where('type','present')->where('user_id', $shortlist->user_id)->first();
                            @endphp
                            @if(!empty($present_address->country_id))
                                {{ $present_address->country->name }}
                            @endif
                          </td>
                          @endif
                          @if(get_setting('member_language_section') == 'on')
                          <td>
                            @if($shortlist->user->member->mothere_tongue != null)
                                {{ \App\Models\MemberLanguage::where('id',$shortlist->user->member->mothere_tongue)->first()->name }}
                            @endif
                          </td>
                          @endif
                          <td class="text-right">
                              @php
                                $interest = \App\Models\ExpressInterest::where('user_id', $shortlist->user_id)->where('interested_by',Auth::user()->id)->first();
                              @endphp
                              @if(empty($interest))
                                <a href="avascript:void(0);" onclick="express_interest({{ $shortlist->user_id }})" id="interest_a_id_{{$shortlist->user_id}}" class="btn btn-soft-primary btn-icon btn-circle btn-sm" title="{{ trans('messages.Express Interest') }}">
                                    <i class="las la-heart"></i>
                                </a>
                              @else
                                <a href="avascript:void(0);" class="btn btn-soft-success btn-icon btn-circle btn-sm" title="{{ trans('messages.Interest Expressed') }}">
                                    <i class="las la-heart"></i>
                                </a>
                              @endif
                              <a onclick="remove_shortlist({{ $shortlist->user_id }})" class="btn btn-soft-danger btn-icon btn-circle btn-sm" title="{{ trans('messages.Remove') }}">
                                  <i class="las la-trash-alt"></i>
                              </a>
                          </td>
                      </tr>
                    @endif

                  @endforeach
              </tbody>
            </table>
            <div class="aiz-pagination">
                {{ $shortlists->links() }}
            </div>
        </div>
    </div>
@endsection

@section('modal')
  @include('modals.confirm_modal')
  @include('modals.package_update_alert_modal')
@endsection

@section('script')
<script type="text/javascript">
    function remove_shortlist(id) {
      $.post('{{ route('member.remove_from_shortlist') }}',
        {
          _token: '{{ csrf_token() }}',
          id: id
        },
        function (data) {
          if (data == 1) {
            $("#shortlisted_member_"+id).hide();
            AIZ.plugins.notify('success', '{{trans('messages.You Have Removed This Member From Shortlist')}}');
          }
          else {
            AIZ.plugins.notify('danger', '{{trans('messages.Something went wrong')}}');
          }
        }
      );
    }

    // Express Interest
    var package_validity = {{ package_validity(Auth::user()->id) }};
    var remaining_interest = {{ get_remaining_value(Auth::user()->id,'remaining_interest') }};
    function express_interest(id)
    {
        if( package_validity == 0 || remaining_interest < 1){
            $('.package_update_alert_modal').modal('show');
        }
        else {
          $('.confirm_modal').modal('show');
          $("#confirm_modal_title").html("{{ trans('messages.Confirm Express Interest') }}");
          $("#confirm_modal_content").html("<p class='fs-14'>{{trans('messages.Remaining Express Interests')}}: "+remaining_interest+" {{trans('messages.Times')}}</p><small class='text-danger'>{{trans('messages.**N.B. Expressing An Interest Will Cost 1 From Your Remaining Interests**')}}</small>");
          $("#confirm_button").attr("onclick","do_express_interest("+id+")");
        }
    }

    function do_express_interest(id){
      $('.confirm_modal').modal('toggle');
      $("#interest_a_id_"+id).removeAttr("onclick");
      $.post('{{ route('express-interest.store') }}',
        {
          _token: '{{ csrf_token() }}',
          id: id
        },
        function (data) {
          if (data == 1) {
            $("#interest_a_id_"+id).attr("class","btn btn-soft-success btn-icon btn-circle btn-sm");
            $("#interest_a_id_"+id).attr("title","{{ trans('messages.Interest Expressed') }}");
            AIZ.plugins.notify('success', '{{trans('messages.Interest Expressed Sucessfully')}}');
          }
          else {
              AIZ.plugins.notify('danger', '{{trans('messages.Something went wrong')}}');
          }
        }
      );
    }

    function package_update_alert(){
      $('.package_update_alert_modal').modal('show');
    }

</script>
@endsection

resources/views/web/member/sidebar.blade.php
<div class="aiz-user-sidenav-wrap pt-4 sticky-top c-scrollbar-light position-relative z-1 shadow-none custom-card">
    <div class="absolute-top-left d-xl-none">
        <button class="btn btn-sm p-2" data-toggle="class-toggle" data-target=".aiz-mobile-side-nav"
                data-same=".mobile-side-nav-thumb">
            <i class="las la-times la-2x"></i>
        </button>
    </div>
    <div class="aiz-user-sidenav rounded overflow-hidden">
        <div class="px-4 text-center mb-4">
            <span class="avatar avatar-md mb-3">
                @if (Auth::user()->image != null)
                    <img src="{{ asset(Auth::user()->image) }}">
                @else
                    <img src="{{ asset('assets/img/avatar-place.png') }}">
                @endif
            </span>
            <h4 class="h5 fw-600">{{ Auth::user()->first_name.' '.Auth::user()->last_name }}</h4>
            <div class="text-center  mb-2">

            </div>
            <div>
                <span class="rating rating-sm">

                </span>
            </div>
            <div class="mb-1">

                <span class="fw-600">

                </span>
                <span>

                </span>
            </div>
        </div>
        <div class="text-center mb-3 px-3">
            <a href="{{ route('member_profile', Auth::user()->id) }}" class="btn btn-block btn-soft-primary">Public
                Profile</a>
        </div>

        <div class="sidemnenu mb-3">
            <ul class="aiz-side-nav-list" data-toggle="aiz-side-menu">

                <li class="aiz-side-nav-item">
                    <a href="{{ route('dashboard') }}" class="aiz-side-nav-link">
                        <i class="las la-home aiz-side-nav-icon"></i>
                        <span class="aiz-side-nav-text">Dashboard</span>
                    </a>
                </li>
{{--                <li class="aiz-side-nav-item">--}}
{{--                    <a href="{{ route('gallery-image.index') }}" class="aiz-side-nav-link">--}}
{{--                        <i class="las la-image aiz-side-nav-icon"></i>--}}
{{--                        <span class="aiz-side-nav-text">Gallery</span>--}}
{{--                    </a>--}}
{{--                </li>--}}
{{--                <li class="aiz-side-nav-item">--}}
{{--                    <a href="{{ route('happy-story.create')}}" class="aiz-side-nav-link">--}}
{{--                        <i class="las la-handshake aiz-side-nav-icon"></i>--}}
{{--                        <span class="aiz-side-nav-text">Happy Story</span>--}}
{{--                    </a>--}}
{{--                </li>--}}

{{--                <li class="aiz-side-nav-item">--}}
{{--                    <a href="#" class="aiz-side-nav-link">--}}
{{--                        <i class="las la-envelope aiz-side-nav-icon"></i>--}}
{{--                        <span class="aiz-side-nav-text">Messages</span>--}}
{{--                    </a>--}}
{{--                </li>--}}

                <li class="aiz-side-nav-item">
                    <a href="{{route('my_interests.index')}}" class="aiz-side-nav-link">
                        <i class="la la-heart-o aiz-side-nav-icon"></i>
                        <span class="aiz-side-nav-text">My Interests</span>
                    </a>
                </li>

                <li class="aiz-side-nav-item">
                    <a href="{{route('my_ignored_list')}}" class="aiz-side-nav-link">
                        <i class="las la-ban aiz-side-nav-icon"></i>
                        <span class="aiz-side-nav-text">Ignored User List</span>
                    </a>
                </li>

                <li class="aiz-side-nav-item">
                    <a href="{{route('change_password')}}" class="aiz-side-nav-link">
                        <i class="las la-key aiz-side-nav-icon"></i>
                        <span class="aiz-side-nav-text">Change Password</span>
                    </a>
                </li>
                <li class="aiz-side-nav-item">
                    <a href="{{ route('profile_settings') }}" class="aiz-side-nav-link">
                        <i class="las la-user aiz-side-nav-icon"></i>
                        <span class="aiz-side-nav-text">Manage Profile</span>
                    </a>
                </li>
                <li class="aiz-side-nav-item">
                    <a href="javascript:void(0);" class="aiz-side-nav-link" onclick="account_deactivation()">
                        @if(Auth::user()->status == 'active' )
                            <i class="las la-lock aiz-side-nav-icon"></i>
                            <span class="aiz-side-nav-text">Deactivate Account</span>
                        @else
                            <i class="las la-unlock aiz-side-nav-icon"></i>
                            <span class="aiz-side-nav-text">Reactive Account</span>
                        @endif
                    </a>
                </li>
            </ul>
        </div>
        <div>
            <a class="btn btn-block btn-primary" href="{{ route('logout') }}">
                <i class="las la-sign-out-alt"></i>
                <span>Logout</span>
            </a>
        </div>
    </div>
</div>