routes/admin.php
<?php


use Illuminate\Support\Facades\Route;

Route::get('/', 'LoginController@index')->name('login');
Route::get('login', 'LoginController@index')->name('login');
Route::post('login', 'LoginController@loginCheck')->name('loginCheck');
Route::group(['middleware' => ['auth:admin', 'adminLanguage']], function () {

    Route::get('dashboard', 'HomeController@index')->name('dashboard');
    Route::resource('category', 'CategoryController');
    Route::resource('user', 'UserController');
    Route::get('userDetails/{id}', 'UserController@userDetails')->name('userDetails');
    Route::get('user/status/{id}/{status}', 'UserController@changeStatus')->name('user.status.change');
    Route::get('user/approve/{id}/{status}', 'UserController@changeApproveStatus')->name('user.approve.change');

    Route::get('profile', 'AdminController@profile')->name('profile');
    Route::post('updateProfile', 'AdminController@updateProfile')->name('updateProfile');
    Route::get('changePassword', 'AdminController@changePassword')->name('changePassword');
    Route::post('updatePassword', 'AdminController@updatePassword')->name('updatePassword');

    Route::post('editProfile', 'HomeController@editProfile')->name('editProfile');
    Route::post('logout', 'LoginController@logout')->name('logout');
    Route::get('/', 'LoginController@index');
    Route::get('dashboard', 'HomeController@index')->name('dashboard');
    Route::get('/logout', 'LoginController@logout')->name('logout');

    Route::post('getState', 'HomeController@getState')->name('getState');
    Route::post('getCity', 'HomeController@getCity')->name('getCity');


    Route::resource('role', 'RoleController');
    Route::resource('permission', 'PermissionController');


    Route::resource('users', 'UserController');
    Route::resource('country', 'CountryController');
    Route::resource('state', 'StateController');
    Route::resource('city', 'CityController');
    Route::get('/pendingUser', 'UserController@pending')->name('pendingUser');
    Route::get('/incompleteUser', 'UserController@incomplete')->name('incompleteUser');
    Route::get('/approvedUser', 'UserController@approved')->name('approvedUser');

    Route::post('getState', 'StateController@getState')->name('getState');
    Route::get('country/status/{id}/{status}', 'CountryController@changeStatus')->name('country.status.change');
    Route::get('state/status/{id}/{status}', 'StateController@changeStatus')->name('state.status.change');
    Route::post('getCity', 'CityController@getCity')->name('getCity');
    Route::get('city/status/{id}/{status}', 'CityController@changeStatus')->name('city.status.change');
    Route::get('role/status/{id}/{status}', 'RoleController@changeStatus')->name('role.status.change');


    Route::resource('page', 'PageController');
    Route::resource('notification', 'NotificationController');

    Route::get('setting', 'SettingController@index')->name('setting');
    Route::get('sendNotification', 'SendController@sendNotification')->name('sendNotification');
    Route::post('sendNotification', 'SendController@sendNotificationProcess')->name('sendNotification');


    Route::post('updateSetting', 'SettingController@updateSetting');

    Route::get('test', 'HomeController@test')->name('test');

    Route::get('export/{id}', 'DirectSellerController@export')->name('export');
    Route::post('customerSearch', 'PurchaseOrderController@customerSearch')->name('customerSearch');

    Route::resource('slider', 'SliderController');
    Route::resource('template', 'TemplateController');
    Route::resource('gotra', 'GotraController');
    Route::resource('workProfile', 'WorkProfileController');
    Route::resource('subAdmin', 'SubAdminController');
    Route::resource('mangalik', 'MangalikController');
    Route::resource('highestEducation', 'HighestEducationController');
    Route::resource('adminLog', 'AdminLogController');
    Route::get('pending-subAdmin', 'SubAdminController@pending')->name('subAdmin.pending');
    Route::get('approved-subAdmin', 'SubAdminController@approved')->name('subAdmin.approved');
    Route::get('rejected-subAdmin', 'SubAdminController@rejected')->name('subAdmin.rejected');
    Route::get('subAdmin/registerStatus/{id}/{status}', 'SubAdminController@changeRegisterStatus')->name('subAdmin.register-status.change');
    Route::get('subAdmin/status/{id}/{status}', 'SubAdminController@changeStatus')->name('subAdmin.status.change');
    Route::post('assignRole', 'SubAdminController@assignRole')->name('assignRole');
    Route::post('rejectSubAdmin', 'SubAdminController@rejectSubAdmin')->name('rejectSubAdmin');
    Route::post('banUser', 'UserController@banUser')->name('banUser');
    Route::get('fileImportExport', 'UserController@fileImportExport')->name('fileImportExport');
    Route::post('fileImport', 'UserController@fileImport')->name('fileImport');
    Route::get('report', 'ReportController@index')->name('report');
    Route::resource('homeBanner', 'HomeBannerController');
    Route::get('analytics', 'HomeController@analytics')->name('analytics');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', 'HomeController@index')->name('home');
Route::get('/verify-email', 'AuthController@verifyEmail')->name('verify-email');
Route::get('/register', 'AuthController@register')->name('register');
Route::get('/contact-us', 'HomeController@contactUs')->name('contact-us');
Route::post('/register', 'AuthController@registerSubmit')->name('register');
Route::get('/login', 'AuthController@login')->name('login');
Route::get('/page/{slug}', 'PageController@index')->name('page');
Route::get('/forgot-password', 'AuthController@forgotPasswordForm')->name('forgot-password');
Route::get('/reset-password/{id}', 'ResetPasswordController@resetPasswordForm')->name('reset-password');
Route::post('/resetPassword', 'ResetPasswordController@resetPassword')->name('resetPassword');
Route::post('/forgotPassword', 'AuthController@forgotPassword')->name('forgotPassword');
Route::post('/login', 'AuthController@loginSubmit')->name('login');
Route::get('/passwordReset', 'AuthController@passwordReset')->name('password.request');
Route::get('/logout', 'AuthController@logout')->name('logout');
Route::get('/happy_stories', 'HomeController@happy_stories')->name('happy_stories');
Route::get('/getState/{id}', 'HomeController@getState')->name('getState');
Route::get('/getCity/{id}', 'HomeController@getCity')->name('getCity');
Route::get('/verify-otp', 'AuthController@verifyOtpForm')->name('verify-otp');
Route::post('/verifyOtp', 'AuthController@verifyOtp')->name('verifyOtp');
Route::get('/admin-form', 'AuthController@adminForm')->name('admin-form');
Route::get('/blocked', 'HomeController@user_account_blocked')->name('user.blocked');
Route::get('resend-otp', 'AuthController@resend_otp')->name('resend-otp');
Route::post('/adminForm', 'AuthController@adminFormSubmit')->name('adminForm');

Route::group(['middleware' => ['auth:web']], function () {
    Route::post('/introduction-update', 'ProfileController@introductionUpdate')->name('introduction-update');
    Route::post('/basic_info_update', 'ProfileController@basic_info_update')->name('basic_info_update');
    Route::post('/update_education_present_status', 'ProfileController@update_education_present_status')->name('update_education_present_status');
    Route::post('/address-update', 'ProfileController@addressUpdate')->name('address-update');
    Route::post('/hobbies-update', 'ProfileController@hobbiesUpdate')->name('hobbies-update');
    Route::post('/recidencies-update', 'ProfileController@recidenciesUpdate')->name('recidencies-update');
    Route::post('/photos-update', 'ProfileController@photosUpdate')->name('photos-update');
    Route::post('/native-address-update', 'ProfileController@nativeAddressUpdate')->name('native-address-update');
    Route::post('/families-update', 'ProfileController@familiesUpdate')->name('families-update');
    Route::post('/education-update', 'ProfileController@educationUpdate')->name('education-update');
    Route::post('/change-email', 'ProfileController@changeEmail')->name('change-email');
    Route::post('/add_to_ignore_list', 'ProfileController@add_to_ignore_list')->name('add_to_ignore_list');
    Route::post('/reportUsers', 'ProfileController@reportUsers')->name('reportUsers');
    Route::post('approve-status-update', 'ProfileController@submitForApproval')->name('approve-status-update');
    Route::post('socialMediaUpdate', 'ProfileController@socialMediaUpdate')->name('socialMediaUpdate');
    Route::get('checkProfile', 'ProfileController@checkProfile')->name('checkProfile');
    Route::get('update_account_deactivation_status', 'ProfileController@update_account_deactivation_status')->name('update_account_deactivation_status');
    Route::group(['middleware' => ['member']], function () {
        Route::get('/dashboard', 'HomeController@dashboard')->name('dashboard');
        Route::get('/memberListing', 'MemberListingController@index')->name('memberListing');
        Route::get('/change_password', 'ProfileController@change_password')->name('change_password');
        Route::get('/profile_settings', 'ProfileController@profile_settings')->name('profile_settings');
        Route::get('/my_interests', 'ProfileController@my_interests')->name('my_interests');

        Route::get('/member_profile/{id}', 'ProfileController@member_profile')->name('member_profile');

        Route::get('/view_contacts', 'ProfileController@view_contacts')->name('view_contacts');
        Route::get('/remove_video', 'ProfileController@remove_video')->name('remove_video');
        Route::get('/add_to_ignore_list', 'ProfileController@add_to_ignore_list')->name('add_to_ignore_list');
        Route::resource('happy-story', 'HappyStoryController');

        Route::get('/ignored-list', 'IgnoredUserController@index')->name('my_ignored_list');
        Route::post('/remove_from_ignored_list-list', 'IgnoredUserController@remove_from_ignored_list')->name('remove_from_ignored_list');

        Route::get('/my-interests', 'ExpressInterestController@index')->name('my_interests.index');
        Route::get('/interest/requests', 'ExpressInterestController@interest_requests')->name('interest_requests');
        Route::post('/interest/accept', 'ExpressInterestController@accept_interest')->name('accept_interest');
        Route::post('/interest/reject', 'ExpressInterestController@reject_interest')->name('reject_interest');
        Route::resource('/express-interest', 'ExpressInterestController');
        Route::get('change-password', 'ProfileController@change_password')->name('change_password');
        Route::post('password_update', 'ProfileController@password_update')->name('password_update');


    });
});

app/Models/HappyStory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class HappyStory extends Model
{

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

resources/views/web/member/happy_story/create.blade.php
<div class="card">
    <div class="card-header">
        <h5 class="mb-0 h6">{{trans('messages.Add Your Story')}}</h5>
    </div>
    <div class="card-body">
      <form action="{{ route('happy-story.store') }}" method="POST">
          @csrf
          <div class="form-group ">
              <label class="form-label" for="name">{{trans('messages.Story Title')}} <span class="text-danger">*</span></label>
              <input type="text" class="form-control" name="title"  placeholder="{{trans('messages.Title')}}" required>
              @error('title')
                  <small class="form-text text-danger">{{ $message }}</small>
              @enderror
          </div>
          <div class="form-group">
              <label class="from-label" for="name">{{trans('messages.Story Details')}} <span class="text-danger">*</span></label>
              <textarea name="details" class="aiz-text-editor form-control" data-buttons='[["font", ["bold", "underline", "italic"]],["para", ["ul", "ol"]],["view", ["undo","redo"]]]' placeholder="Type.." data-min-height="200"></textarea>
              @error('details')
                  <small class="form-text text-danger">{{ $message }}</small>
              @enderror
          </div>
          <div class="form-group">
              <label class="from-label" for="name">{{trans('messages.Partner Name')}} <span class="text-danger">*</span></label>
              <input type="text" class="form-control" name="partner_name"  placeholder="{{trans('messages.Partner Name')}}" required>
              @error('partner_name')
                  <small class="form-text text-danger">{{ $message }}</small>
              @enderror
          </div>
          <div class="form-group">
              <label class="form-label" for="signinSrEmail">{{trans('messages.Photos')}} <span class="text-danger">*</span></label>
              <div class="input-group" data-toggle="aizuploader" data-type="image" data-multiple="true">
                  <div class="input-group-prepend">
                      <div class="input-group-text bg-soft-secondary font-weight-medium">{{ trans('messages.Browse')}}</div>
                  </div>
                  <div class="form-control file-amount">{{ trans('messages.Choose File') }}</div>
                  <input type="hidden" name="photos" class="selected-files" required>
              </div>
              <div class="file-preview box sm">
              </div>
              @error('photos')
                  <small class="form-text text-danger">{{ $message }}</small>
              @enderror
          </div>
          <div class="form-group ">
    					<label class="from-label">{{trans('messages.Video Provider')}}</label>
  						<select class="form-control aiz-selectpicker" name="video_provider" id="video_provider">
  							<option value="youtube">{{trans('messages.Youtube')}}</option>
  							<option value="dailymotion">{{trans('messages.Dailymotion')}}</option>
  							<option value="vimeo">{{trans('messages.Vimeo')}}</option>
  						</select>
  				</div>
  				<div class="form-group ">
  					<label class="from-label">{{trans('messages.Video Link')}}</label>
  						<input type="text" class="form-control" name="video_link" placeholder="{{ trans('messages.Video Link') }}">
              <small class="text-muted">{{translate("Use proper link without extra parameter. Don't use short share link/embeded iframe code.")}}</small>
  				</div>
          <div class="form-group mb-0 text-right">
              <button type="submit" class="btn btn-primary">{{trans('messages.Save')}}</button>
          </div>
        </from>
    </div>
</div>

resources/views/web/member/happy_story/index.blade.php
@extends('web.layouts.member_panel')
@section('panel_content')
      @if(Auth::user()->membership == 2)

        @php $happy_story = \App\Models\HappyStory::where('user_id', Auth::user()->id)->first(); @endphp
        @if(empty($happy_story))
           @include('web.member.happy_story.create')
        @else
          @include('web.member.happy_story.view')
        @endif

      @else
        <div class="card">
            <div class="card-header">
                <h5 class="mb-0 h6">{{trans('messages.Your Story')}}</h5>
            </div>
            <div class="card-body">
                <h5 class="text-center">{{ trans('messages.Please Upgrade To Premium Membership To Post Your Story') }}</h5>
                <a href="{{ route('packages') }}" class="btn btn-block btn-primary mt-4 mb-6">{{ trans('messages.Get Premium Membership') }}</a>
            </div>
        </div>
      @endif
@endsection

resources/views/web/member/happy_story/view.blade.php
<div class="card">
    <div class="card-header">
        <h5 class="mb-0 h6">{{ trans('messages.Story Details') }}</h5>
    </div>
    <div class="card-body">
      <div class="row align-items-center">
          <div class="col-8">
              <span class="h6">{{ $happy_story->title }}</span>
          </div>
          <div class="col-4 text-right">
              <span >
                {{ trans('messages.Posted By:').' '.$happy_story->user->first_name.' '.$happy_story->user->last_name }}
              </span>
          </div>
      </div>
      <div class="aiz-carousel dots-inside-bottom mobile-img-auto-height mt-4" data-arrows="true" data-dots="true" data-autoplay="true">
          @if ($happy_story->photos != null)
              @foreach (explode(',',$happy_story->photos) as $key => $photo)
                  <div class="carousel-box">
                      <img class="d-block w-100 lazyload rounded h-200px h-lg-380px img-fit" src="{{ asset('assets/img/placeholder-rect.jpg') }}" data-src="{{ uploaded_asset($photo) }}" alt="{{ $key }} offer">
                  </div>
              @endforeach
          @endif
      </div>
      <div>{{ trans('messages.Post Time:').' '.$happy_story->created_at }}</div>
      <div class="overflow-hidden mt-4">@php echo $happy_story->details; @endphp</div>
      <div class="p-4">
          <div class="embed-responsive embed-responsive-16by9">
              @if ($happy_story->video_provider == 'youtube' && isset(explode('=', $happy_story->video_link)[1]))
                  <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{ explode('=', $happy_story->video_link)[1] }}"></iframe>
              @elseif ($happy_story->video_provider == 'dailymotion' && isset(explode('video/', $happy_story->video_link)[1]))
                  <iframe class="embed-responsive-item" src="https://www.dailymotion.com/embed/video/{{ explode('video/', $happy_story->video_link)[1] }}"></iframe>
              @elseif ($happy_story->video_provider == 'vimeo' && isset(explode('vimeo.com/', $happy_story->video_link)[1]))
                  <iframe src="https://player.vimeo.com/video/{{ explode('vimeo.com/', $happy_story->video_link)[1] }}" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
              @endif
          </div>
      </div>
    </div>
</div>